name: flagenv
on: push

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: checkout code
      uses: actions/checkout@v1
    - name: test
      run: go test ./...
